# Generated by Django 3.1.6 on 2022-10-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='post_advance_links',
            field=models.BooleanField(default=False, verbose_name='高级链接'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='read_time',
            field=models.BooleanField(default=False, verbose_name='阅读时间'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_tags',
            field=models.BooleanField(default=False, verbose_name='显示tag'),
        ),
    ]
