# Generated by Django 4.1.7 on 2023-10-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_sitesetting_show_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.TextField(null=True, verbose_name='描述'),
        ),
    ]
